# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "680dd8b88e9671eb5cbf6d1feff964e5"
name = "myapp"
application_url = "https://telephony-llc-forming-fellow.trycloudflare.com"
embedded = true
handle = "myapp-1154"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aj-creativee.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_files,write_products,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://telephony-llc-forming-fellow.trycloudflare.com/auth/callback",
  "https://telephony-llc-forming-fellow.trycloudflare.com/auth/shopify/callback",
  "https://telephony-llc-forming-fellow.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://telephony-llc-forming-fellow.trycloudflare.com/app/api-popup"
subpath = "api-popup"
prefix = "apps"


[pos]
embedded = false
